const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');
const os = require('os');

const projectRoot = path.join(__dirname, '..');
const vendorDir = path.join(projectRoot, 'vendor');
if (!fs.existsSync(vendorDir)) {
  fs.mkdirSync(vendorDir, { recursive: true });
}

function toBase64(filePath) {
  return fs.readFileSync(filePath).toString('base64');
}

function requireFile(filePath, description) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`${description} 未找到: ${filePath}`);
  }
}

const rarExeSource = 'C:\\Program Files\\WinRAR\\rar.exe';
const sfxSource = 'C:\\Program Files\\WinRAR\\Default.SFX';
requireFile(rarExeSource, 'WinRAR 命令行工具 (rar.exe)');
requireFile(sfxSource, 'WinRAR 自解压模块 (Default.SFX)');

// 从 Electron 运行时提取默认图标
const electronExe = path.join(projectRoot, 'node_modules', 'electron', 'dist', 'electron.exe');
requireFile(electronExe, 'Electron 运行时 (electron.exe)');

const tempIcon = path.join(os.tmpdir(), `dt-electron-icon-${Date.now()}.ico`);
const psScript = `
Add-Type -AssemblyName System.Drawing
$icon = [System.Drawing.Icon]::ExtractAssociatedIcon('${electronExe.replace(/\\/g, '\\\\')}')
$stream = [System.IO.File]::OpenWrite('${tempIcon.replace(/\\/g, '\\\\')}')
$icon.Save($stream)
$stream.Close()
`;
const psFile = path.join(os.tmpdir(), `dt-extract-icon-${Date.now()}.ps1`);
fs.writeFileSync(psFile, psScript, 'utf8');
childProcess.execSync(`powershell -ExecutionPolicy Bypass -File "${psFile}"`, { windowsHide: true });
fs.unlinkSync(psFile);
requireFile(tempIcon, '提取的 Electron 默认图标');

const data = {
  rarExeBase64: toBase64(rarExeSource),
  sfxModuleBase64: toBase64(sfxSource),
  electronIconBase64: toBase64(tempIcon)
};

const outputPath = path.join(vendorDir, 'embedded-binaries.js');
const output = `// Auto-generated by scripts/encode-vendor.js
// 嵌入 WinRAR 命令行工具、自解压模块以及 Electron 默认图标，
// 使独立 EXE 导出功能无需在运行电脑上安装 WinRAR。
// 这些二进制文件均为对应软件的未修改组件。
module.exports = ${JSON.stringify(data, null, 2)};
`;
fs.writeFileSync(outputPath, output, 'utf8');
fs.unlinkSync(tempIcon);

console.log(`已生成 ${outputPath}`);
console.log(`rar.exe: ${data.rarExeBase64.length} bytes base64`);
console.log(`Default.SFX: ${data.sfxModuleBase64.length} bytes base64`);
console.log(`electron-icon.ico: ${data.electronIconBase64.length} bytes base64`);
